SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [RE_AGENTS].[PROJECTS](
	[PROJECT_ID] [int] IDENTITY(1,1) NOT NULL,
	[PROJECT_NAME] [varchar](max) NULL,
	[PROJECT_DESCRIPTION] [varchar](max) NULL,
	[URL_VIDEO_GENERAL] [varchar](max) NULL,
	[URL_VIDEO_INDIVIDUAL] [varchar](max) NULL,
	[URL_VIDEO_AMENITIES] [varchar](max) NULL,
	[URL_VIDEO_FAMILY] [varchar](max) NULL,
	[URL_VIDEO_ZONE] [varchar](max) NULL,
	[URL_VIDEO_LUXURY] [varchar](max) NULL,
	[URL_BROCHURE] [varchar](max) NULL,
	[URL_PHOTO_COVER] [varchar](max) NULL,
	[ENTERPRISE_ID] [int] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [RE_AGENTS].[PROJECTS] ADD PRIMARY KEY CLUSTERED 
(
	[PROJECT_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
